version: '1.0'
stages:
  - clone
  - prepare
  - pre-deploy
  - deploy
  - post-deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: clone
    git: CF-default

  setup:
    image: alpine:3.7
    stage: prepare
    title: generate GCP shared credentials file
    commands:
      - mkdir -p .gcloud
      - echo -n $GCP_CREDENTIALS_FILE | base64 -d > ${PWD}/.gcloud/keyfile.json
      - cf_export GCP_SHARED_CREDENTIALS_FILE=${PWD}/.gcloud/keyfile.json

  lint_build:
    image: nikolaik/python-nodejs:latest
    title: lint
    stage: pre-deploy
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - npm install package.json
      - npm install -g typescript
      - ls node_modules/
      - npm run build

  unitTest:
    image: nikolaik/python-nodejs:latest
    title: Unit Test using firebase cloud shell
    stage: pre-deploy
    working_directory: ${{main_clone}}/ts-sandbox
    commands:
      - npm install -g firebase-tools@6.8.0
      - firebase use --add saas-cloud-prototype 
      - pip install -r requirements.txt
      - python tests/curl.py
      
  deploy:
    image: codefresh/serverless:1.28
    stage: deploy
    title: deploy to GCP with serverless framework
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - npm install serverless-google-cloudfunctions
      - serverless deploy
    when:
      condition:
            all:
              checkUnitTestPass: '"${{CF_UNIT_TEST_STATUS}}" == "SUCCESS"'
              
  package:
    image: codefresh/serverless:1.28
    stage: post-deploy
    title: package serverless service
    working_directory: ${{main_clone}}/ts-sandbox/functions
    commands:
      - echo "Tag and push package to Cloud Storage from .serverless folder"
    when:
      condition:
            all:
              checkUnitTestPass: '"${{CF_UNIT_TEST_STATUS}}" == "SUCCESS"'
